version: "3.9"

services:
  nginx:
    build:
      context: .
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      - PROFILE=${PROFILE}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
